version: "2"

services:
  timetable:
    ports:
      - "80:80"
    build: .
    restart: unless-stopped

  redis:
    image: docker.io/redis:alpine3.18
    ports:
      - "6379:6379"
    restart: unless-stopped
