version: "2"

services:
  timetable:
    ports:
      - "80:80"
    build: .
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}

  redis:
    image: redis:7.2.2-alpine3.18
    ports:
      - "6379:6379"
    restart: unless-stopped
